version: '3'
services:
  web:
   image: webdevops/php-apache-dev:7.4
   depends_on:
     - mailpit
   links:
     - mailpit
   volumes:
     - ./:/var/www/html/cypress-mh-tests/
   ports:
     - "3000:80"
   environment:
     - PHP_DISPLAY_ERRORS=E_ALL
     - WEB_DOCUMENT_ROOT=/var/www/html
   privileged: true
   devices:
     - /dev/fuse:/dev/fuse

  mailpit:
    image: axllent/mailpit
    ports:
      - "8090:8025"
      - "1026:1025"
